# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path and theme to your oh-my-zsh installation.
export ZSH="/Users/nyustetirados/.oh-my-zsh"
ZSH_THEME="robbyrussell"

 # Bug in MacOS Sierra. I need this so the terminal remember the ssh keys.
# http://apple.stackexchange.com/questions/254468/macos-sierra-doesn-t-seem-to-remember-ssh-keys-between-reboots
# -----------------------------------------------------------------------
ssh-add -A 2>/dev/null;

# My Path
# ----------------
export PATH="$PATH":~/bin
export ANDROID_HOME=~/Library/Android/sdk # Android SDK
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools # Android Tools
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export NVM_DIR="$HOME/.nvm"

# Homebrew
# -------------
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# My Alias
# -------------
alias s='git status'
alias op='open . -a Finder'
alias stree='open . -a SourceTree'
alias myip='ipconfig getifaddr en0'
alias clean_camera='sudo killall VDCAssistant'

alias and_shell='adb shell input text'
alias and_screenshot="adb shell screencap -p > ~/Desktop/android_screen.png"
alias and_clean_proxy='adb shell rm -f /data/local/tmp/proxy-config'

alias odo_streamer='ssh -o StrictHostKeyChecking=no -l nicoyuste 192.168.1.24 "java -jar Documents/repos/bundle/Streamer-1.0.jar"'

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git, 
  brew, 
  gem, 
  gitfast, 
  git-extras,
  gradle
)

source $ZSH/oh-my-zsh.sh
unsetopt share_history
setopt no_share_history